OUTPUT_DIR: '/data/bhfs/code/colonoscopy_segmentation/output/unet11/dicelossv1_down4'

MODEL:
  MODEL: 'UNet11'
  LOSS: 'DiceLossV1'

SOLVER:
  LR: 0.01
  EPOCHS: 2000
  DRAW: True

DATA:
  DOWN_SAMPLE_RATE: (4., )