OUTPUT_DIR: '/data/bhfs/code/colonoscopy_segmentation/output/unet16/layer4_dicelossv1_dsv2_down4'

MODEL:
  MODEL: 'UNet16Layer4'
  LOSS: 'DiceLossV1'
  DEEP_SUP: 'v2'

SOLVER:
  LR: 0.01
  EPOCHS: 2000
  DRAW: True

DATA:
  DOWN_SAMPLE_RATE: (4., )