OUTPUT_DIR: '/data/bhfs/code/colonoscopy_segmentation/output/gcn/bce_down4'

MODEL:
  MODEL: 'gcn'
  LOSS: 'BceLoss'

SOLVER:
  LR: 0.001
  EPOCHS: 2000
  DRAW: True

DATA:
  DENSE_CROP_MERGE_METHOD: 'or'
  DOWN_SAMPLE_RATE: 4.